In [5]:
import torch

In [8]:
x = torch.empty(5,3)
x = torch.rand(5,3)
x

tensor([[0.2648, 0.9044, 0.2377],
        [0.6494, 0.0762, 0.1962],
        [0.1844, 0.6847, 0.1791],
        [0.0336, 0.1768, 0.8428],
        [0.3984, 0.5310, 0.5891]])

In [9]:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
x = torch.Tensor(5,3)
x = torch.Tensor([5.5, 3.3])
x

tensor([5.5000, 3.3000])

In [12]:
x = torch.ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
y = torch.randn_like(x, dtype =  torch.double)
y

tensor([[ 0.7900,  2.1798,  0.3178],
        [ 1.3783, -0.4384, -0.5336],
        [-1.7739,  1.7964,  0.6644],
        [-0.3803, -1.6044,  0.5897],
        [ 1.0330,  0.2465,  0.4097]], dtype=torch.float64)

In [16]:
y.size()

torch.Size([5, 3])

In [17]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
y = torch.rand(5,3)

In [19]:
y

tensor([[0.8849, 0.8194, 0.5751],
        [0.4779, 0.4180, 0.8854],
        [0.6750, 0.0152, 0.0176],
        [0.5263, 0.2297, 0.7916],
        [0.1813, 0.5682, 0.4616]])

In [20]:
z = x + y
z

tensor([[1.8849, 1.8194, 1.5751],
        [1.4779, 1.4180, 1.8854],
        [1.6750, 1.0152, 1.0176],
        [1.5263, 1.2297, 1.7916],
        [1.1813, 1.5682, 1.4616]])

In [21]:
z = torch.add(x,y)
z

tensor([[1.8849, 1.8194, 1.5751],
        [1.4779, 1.4180, 1.8854],
        [1.6750, 1.0152, 1.0176],
        [1.5263, 1.2297, 1.7916],
        [1.1813, 1.5682, 1.4616]])

In [22]:
y.add_(x)
y=y+x

In [26]:
a = torch.rand(4,4)
a

tensor([[0.5751, 0.9356, 0.3791, 0.1352],
        [0.4014, 0.4993, 0.0644, 0.6351],
        [0.4766, 0.4226, 0.2346, 0.8383],
        [0.7004, 0.9771, 0.5264, 0.7736]])

In [27]:
b = torch.rand(4,4)
b

tensor([[0.1554, 0.0012, 0.0402, 0.9738],
        [0.4086, 0.5894, 0.2223, 0.3030],
        [0.3552, 0.9324, 0.9359, 0.5197],
        [0.6570, 0.9156, 0.7166, 0.6212]])

In [28]:
c= torch.empty(4,4)
torch.add(a,b,out=c)
c

tensor([[0.7305, 0.9367, 0.4193, 1.1089],
        [0.8099, 1.0888, 0.2868, 0.9381],
        [0.8318, 1.3550, 1.1705, 1.3580],
        [1.3574, 1.8927, 1.2430, 1.3947]])

In [29]:
a

tensor([[0.5751, 0.9356, 0.3791, 0.1352],
        [0.4014, 0.4993, 0.0644, 0.6351],
        [0.4766, 0.4226, 0.2346, 0.8383],
        [0.7004, 0.9771, 0.5264, 0.7736]])

In [30]:
a[:,1]


tensor([0.9356, 0.4993, 0.4226, 0.9771])

In [31]:
x = torch.rand(4,4)
x

tensor([[0.4518, 0.6425, 0.3901, 0.3886],
        [0.2059, 0.4962, 0.2582, 0.5172],
        [0.5780, 0.2878, 0.1654, 0.8074],
        [0.0224, 0.1646, 0.5955, 0.0638]])

In [32]:
x.shape

torch.Size([4, 4])

In [34]:
y = x.view(16)
y.shape

torch.Size([16])

In [35]:
y = x.view(-1,8)
y.shape

torch.Size([2, 8])

In [36]:
x = torch.randn(1)
x

tensor([-1.0658])

In [37]:
x.item()

-1.0658053159713745

In [38]:
x = torch.rand(3,3)
x

tensor([[0.1965, 0.6484, 0.6572],
        [0.2955, 0.5406, 0.5721],
        [0.5354, 0.9379, 0.3169]])

In [39]:
x[0,0]

tensor(0.1965)

In [40]:
y=x[0,0]

In [41]:
y

tensor(0.1965)

In [42]:
y.item()


0.19654494524002075

In [45]:
x

tensor([[0.1965, 0.6484, 0.6572],
        [0.2955, 0.5406, 0.5721],
        [0.5354, 0.9379, 0.3169]])

In [46]:
y=x.numpy()
y[0,0]

np.float32(0.19654495)

In [47]:
import numpy as np

In [48]:
a = np.ones(3)

In [49]:
a

array([1., 1., 1.])

In [53]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1.], dtype=torch.float64)

In [54]:
x

tensor([[0.1965, 0.6484, 0.6572],
        [0.2955, 0.5406, 0.5721],
        [0.5354, 0.9379, 0.3169]])

In [58]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)